# Generated by Django 5.1.4 on 2024-12-27 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('specialization', models.CharField(max_length=255, verbose_name='Специализация')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='end_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='procedure_data',
            field=models.DateField(default='1900-01-01', verbose_name='Дата приема'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='medical.medicalservice', verbose_name='Процедура'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalservice',
            name='specialization',
            field=models.CharField(default='', max_length=255, verbose_name='Специализация'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(verbose_name='Время приема'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to='medical.doctor', verbose_name='Врач'),
        ),
    ]
